### ISSUE TITLE
Improving by learning from other projects(discussion)

### ISSUE THREAD

**Issue by jasan-s** [hideckies/nft-collectibles-blender-python#1]
Thanks for open sourcing. I would love to help improve this lib, found couple other projects that deal with Generative Art , See below:
- [Blend_My_NFTs](https://github.com/torrinworx/Blend_My_NFTs)  (3d)
- [Hashlips](https://github.com/HashLips/hashlips_art_engine) (2D)

**Comment by hideckies** [comment]
Thanks for your information! I'll check it later;)

**Comment by NinjaDesBois** [comment]
hi , please can you help me with the Start generating metadata...
ERROR: Properties duplicate. Please run again.

i run again but i got the same problem

**Comment by hideckies** [comment]
@NinjaDesBois
> hi , please can you help me with the Start generating metadata... ERROR: Properties duplicate. Please run again.
> 
> i run again but i got the same problem

Hi,  
please set **TOTAL_CHARACTERS = 2** in settings in the *gen_metadata.py*, then probably success. If you still get an error, try again and again until success.


The error occurs frequently if there are not enough items in each list againt the **TOTAL_CHARACTERS** in *gen_metadata.py*:

```py
# gen_metadata.py

# ----Settings---------------------------------------------------------------------------

# ...

# List
list_bg = [
    "green", "navy", "red", "yellow"
]
list_body = [
    "shirt", "tanktop", "zombie"
]
list_head = [
    "devil", "dragon", "frog", "pixel", "warrior"
]
# --------------------------------------------------------------------------------------------
```


*The demo project also does not have enough parts, so it occurs frequently.  So I'll add more parts items and update in a few days.

**Comment by NinjaDesBois** [comment]
Thank you very much,  I try with 3 and it works. Thank a lot for this repo
